// Code generated by protoc-gen-go.
// source: todo.proto
// DO NOT EDIT!

/*
Package todo is a generated protocol buffer package.

It is generated from these files:
	todo.proto

It has these top-level messages:
	Todo
	TodoList
	Empty
*/
package todo

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

import (
	context "golang.org/x/net/context"
	grpc "google.golang.org/grpc"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type Todo struct {
	Name string `protobuf:"bytes,1,opt,name=name" json:"name,omitempty"`
}

func (m *Todo) Reset()                    { *m = Todo{} }
func (m *Todo) String() string            { return proto.CompactTextString(m) }
func (*Todo) ProtoMessage()               {}
func (*Todo) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{0} }

type TodoList struct {
	Todos []*Todo `protobuf:"bytes,1,rep,name=todos" json:"todos,omitempty"`
}

func (m *TodoList) Reset()                    { *m = TodoList{} }
func (m *TodoList) String() string            { return proto.CompactTextString(m) }
func (*TodoList) ProtoMessage()               {}
func (*TodoList) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{1} }

func (m *TodoList) GetTodos() []*Todo {
	if m != nil {
		return m.Todos
	}
	return nil
}

type Empty struct {
}

func (m *Empty) Reset()                    { *m = Empty{} }
func (m *Empty) String() string            { return proto.CompactTextString(m) }
func (*Empty) ProtoMessage()               {}
func (*Empty) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{2} }

func init() {
	proto.RegisterType((*Todo)(nil), "todo.Todo")
	proto.RegisterType((*TodoList)(nil), "todo.TodoList")
	proto.RegisterType((*Empty)(nil), "todo.Empty")
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion2

// Client API for DoSomething service

type DoSomethingClient interface {
	// Sends a greeting
	AddTodo(ctx context.Context, in *Todo, opts ...grpc.CallOption) (*Empty, error)
	ListTodos(ctx context.Context, in *Empty, opts ...grpc.CallOption) (*TodoList, error)
}

type doSomethingClient struct {
	cc *grpc.ClientConn
}

func NewDoSomethingClient(cc *grpc.ClientConn) DoSomethingClient {
	return &doSomethingClient{cc}
}

func (c *doSomethingClient) AddTodo(ctx context.Context, in *Todo, opts ...grpc.CallOption) (*Empty, error) {
	out := new(Empty)
	err := grpc.Invoke(ctx, "/todo.DoSomething/AddTodo", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *doSomethingClient) ListTodos(ctx context.Context, in *Empty, opts ...grpc.CallOption) (*TodoList, error) {
	out := new(TodoList)
	err := grpc.Invoke(ctx, "/todo.DoSomething/ListTodos", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// Server API for DoSomething service

type DoSomethingServer interface {
	// Sends a greeting
	AddTodo(context.Context, *Todo) (*Empty, error)
	ListTodos(context.Context, *Empty) (*TodoList, error)
}

func RegisterDoSomethingServer(s *grpc.Server, srv DoSomethingServer) {
	s.RegisterService(&_DoSomething_serviceDesc, srv)
}

func _DoSomething_AddTodo_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Todo)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DoSomethingServer).AddTodo(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/todo.DoSomething/AddTodo",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DoSomethingServer).AddTodo(ctx, req.(*Todo))
	}
	return interceptor(ctx, in, info, handler)
}

func _DoSomething_ListTodos_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Empty)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DoSomethingServer).ListTodos(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/todo.DoSomething/ListTodos",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DoSomethingServer).ListTodos(ctx, req.(*Empty))
	}
	return interceptor(ctx, in, info, handler)
}

var _DoSomething_serviceDesc = grpc.ServiceDesc{
	ServiceName: "todo.DoSomething",
	HandlerType: (*DoSomethingServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "AddTodo",
			Handler:    _DoSomething_AddTodo_Handler,
		},
		{
			MethodName: "ListTodos",
			Handler:    _DoSomething_ListTodos_Handler,
		},
	},
	Streams: []grpc.StreamDesc{},
}

var fileDescriptor0 = []byte{
	// 163 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x09, 0x6e, 0x88, 0x02, 0xff, 0xe2, 0xe2, 0x2a, 0xc9, 0x4f, 0xc9,
	0xd7, 0x2b, 0x28, 0xca, 0x2f, 0xc9, 0x17, 0x62, 0x01, 0xb1, 0x95, 0xa4, 0xb8, 0x58, 0x42, 0x80,
	0xb4, 0x90, 0x10, 0x17, 0x4b, 0x5e, 0x62, 0x6e, 0xaa, 0x04, 0xa3, 0x02, 0xa3, 0x06, 0x67, 0x10,
	0x98, 0xad, 0xa4, 0xc3, 0xc5, 0x01, 0x92, 0xf3, 0xc9, 0x2c, 0x2e, 0x11, 0x52, 0xe0, 0x62, 0x05,
	0xa9, 0x2f, 0x06, 0x2a, 0x60, 0xd6, 0xe0, 0x36, 0xe2, 0xd2, 0x03, 0x9b, 0x04, 0x92, 0x0e, 0x82,
	0x48, 0x28, 0xb1, 0x73, 0xb1, 0xba, 0xe6, 0x16, 0x94, 0x54, 0x1a, 0xc5, 0x73, 0x71, 0xbb, 0xe4,
	0x07, 0xe7, 0xe7, 0xa6, 0x96, 0x64, 0x64, 0xe6, 0xa5, 0x0b, 0xa9, 0x70, 0xb1, 0x3b, 0xa6, 0xa4,
	0x80, 0x2d, 0x41, 0xd2, 0x25, 0xc5, 0x0d, 0x61, 0x83, 0xb5, 0x28, 0x31, 0x08, 0x69, 0x71, 0x71,
	0x82, 0xec, 0x01, 0x49, 0x15, 0x0b, 0x21, 0xcb, 0x49, 0xf1, 0x21, 0x34, 0x81, 0x54, 0x28, 0x31,
	0x24, 0xb1, 0x81, 0x3d, 0x60, 0x0c, 0x08, 0x00, 0x00, 0xff, 0xff, 0x37, 0xe5, 0x71, 0x76, 0xce,
	0x00, 0x00, 0x00,
}
